# Generated by Django 5.2.8 on 2025-11-19 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(choices=[('Unas', 'Uñas'), ('Corte_Pelo', 'Corte de Pelo'), ('Tintura', 'Tintura')], default='Corte_Pelo', max_length=50, verbose_name='Servicio')),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha y Hora')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('duracion_minutos', models.IntegerField(default=30)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nombre', models.CharField(max_length=100)),
                ('fecha_hora_inicio', models.DateTimeField()),
                ('fecha_hora_fin', models.DateTimeField(editable=False)),
                ('confirmado', models.BooleanField(default=False)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio')),
            ],
            options={
                'ordering': ['fecha_hora_inicio'],
                'unique_together': {('servicio', 'fecha_hora_inicio')},
            },
        ),
    ]
