# Generated by Django 5.2.8 on 2025-11-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
