# Generated by Django 5.2.8 on 2025-11-19 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_servicio_descripcion_servicio_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='turno',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
