# Generated by Django 5.2.8 on 2025-11-19 04:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_convert_reserva_servicio_to_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='turno',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.turno'),
        ),
    ]
